Dataset:
  DataDir: "data/04-09-12-19-29"

ChessboardParam:
  # description: number of corner along the left side of chessboard in pixel coordinate (not the number of grid)
  CornerNumAlongLeftSide: 7
  # description: number of corner along the bottom side of chessboard in pixel coordinate (not the number of grid)
  CornerNumAlongBottomSide: 5
  # description: grid size of chessboard in meter
  GridSize: 0.08
  # description: color of the grid in the bottom left of chessboard
  CornerColor: "black"

SensorParam:
  LiDAR: Horizon

AlgorithmParam:
  # description: distance threshold for RANSAC (unit: meter)
  plane_fitting_threshold: 0.02
  # description: RANSAC seed (None or int)
  ransac_seed: 233
  # description: downsample method (uniform or mean)
  voxel_grid_method: "uniform"
  # description: whether to save the pointcloud's chessboard for reuse (True or False)
  reset_segmentation: True
  boundary_threshold: 1.8

OtherParam:
  # description: True or False
  use_hash_map_reproject: False
  # description: True or False
  use_plane_refine: True